### ISSUE TITLE
External files not loading

### ISSUE THREAD

**Issue by weboverhauls** [paypal/accessible-html5-video-player#105]
Demo's broken; external files not loading.
http://paypal.github.io/accessible-html5-video-player/
cc @hozefaj

**Comment by hozefaj** [comment]
Will check on this today.

**Comment by hozefaj** [comment]
@weboverhauls The issue here is that http://paypal.github.io/accessible-html5-video-player/ is not regonizing relative paths. So I added absolute paths to the files. But js files are being blocked since http://paypal.github.io/ considers github.com a different domain.

Looking into a way around the issue. If you some way to fix it, let me know.

**Comment by hozefaj** [comment]
@weboverhauls So I fixed it by moving `media` and `image` files into the docs folder since they are specific to our example not specific to the code base.

Also for now, `css` and `js`, I am copying over into the `docs` folder as well. Create a `npm` [command](https://github.com/paypal/accessible-html5-video-player/blob/master/package.json#L54) for it.

**Comment by weboverhauls** [comment]
Confirmed, thank you!
